<a href="https://colab.research.google.com/github/Park-ByungKyu/MLpractice/blob/main/pypractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###  1.4 필수 라이브러리와 도구들

In [2]:
import numpy as np

In [10]:
x = np.array([[0,2,0],[4,5,0]])
print("x:\n", x)

x:
 [[0 2 0]
 [4 5 0]]


In [11]:
from scipy import sparse

In [12]:
eye = np.eye(4)
print("Numpy 배열:\n", eye)

Numpy 배열:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
sparse_matrix = sparse.csr_matrix(x)
print("CSR 행렬:\n", sparse_matrix)

CSR 행렬:
   (0, 1)	2
  (1, 0)	4
  (1, 1)	5
